version: '3.8'

services:
  # -------------------- 데이터베이스 서비스 --------------------
  HwanYulMate-db:
    image: mysql:8.0
    container_name: HwanYulMate-db
    restart: always # 컨테이너 비정상 종료 시 항상 재시작
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - HwanYulMate-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------- Redis 서비스 (실제 서비스 최적화) --------------------
  HwanYulMate-redis:
    image: redis:7.2-alpine
    container_name: HwanYulMate-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf  # Redis 설정 파일 마운트
    networks:
      - HwanYulMate-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}  # 운영환경 비밀번호 설정 가능
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    command: >
      redis-server 
      --appendonly yes 
      --maxmemory 512mb 
      --maxmemory-policy allkeys-lru 
      --tcp-keepalive 300 
      --timeout 300
      --tcp-backlog 511
      --databases 16
      --save 900 1
      --save 300 10
      --save 60 10000


# -------------------- 볼륨 및 네트워크 정의 --------------------
volumes:
  mysql_data:
  redis_data:

networks:
  HwanYulMate-network:
    driver: bridge